In [ ]:
import pandas as pd
df=pd.read_csv('data.csv')

In [ ]:
df.head(5)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [ ]:
x=df[['bedrooms','bathrooms','sqft_living','sqft_lot','floors','waterfront','view','condition','sqft_above','sqft_basement','yr_built','yr_renovated']]
y=df[['price']]

In [ ]:
df.isnull().any()

date             False
price            False
bedrooms         False
bathrooms        False
sqft_living      False
sqft_lot         False
floors           False
waterfront       False
view             False
condition        False
sqft_above       False
sqft_basement    False
yr_built         False
yr_renovated     False
street           False
city             False
statezip         False
country          False
dtype: bool

In [ ]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
dt_model=DecisionTreeRegressor(max_depth=5,random_state=42)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
dt_model.fit(x_train, y_train)

DecisionTreeRegressor(max_depth=5, random_state=42)

In [ ]:
y_pred = dt_model.predict(x_test)

In [ ]:
print(y_pred)

[ 612736.77731195  346071.31586993  474746.61829186  381076.35672827
  512889.72181163  474746.61829186  381076.35672827  381076.35672827
  989791.38709677  474746.61829186  474746.61829186  767001.02148205
  512889.72181163  512889.72181163  381076.35672827  612736.77731195
  474746.61829186  346071.31586993  346071.31586993  381076.35672827
  801462.51851852  381076.35672827  512889.72181163  621337.07050092
  474746.61829186  621337.07050092 1450522.94949485  989791.38709677
  767001.02148205  512889.72181163  346071.31586993  474746.61829186
  808757.4         474746.61829186  621337.07050092  381076.35672827
 1276169.03703704  512889.72181163  512889.72181163  989791.38709677
  474746.61829186  512889.72181163  474746.61829186  512889.72181163
  474746.61829186  801462.51851852  474746.61829186  381076.35672827
  512889.72181163  381076.35672827  512889.72181163  381076.35672827
  612736.77731195  474746.61829186  381076.35672827  474746.61829186
  474746.61829186  808757.4        1908500.          381076.35672827
  381076.35672827  512889.72181163  474746.61829186  474746.61829186
  989791.38709677  512889.72181163  474746.61829186  767001.02148205
  767001.02148205  621337.07050092  381076.35672827  512889.72181163
 1276169.03703704  808757.4         612736.77731195  346071.31586993
  381076.35672827  767001.02148205  381076.35672827  381076.35672827
  454466.66666667  381076.35672827  767001.02148205  474746.61829186
  381076.35672827  612736.77731195  989791.38709677  767001.02148205
  474746.61829186  381076.35672827  767001.02148205  346071.31586993
  381076.35672827  381076.35672827  989791.38709677  381076.35672827
  381076.35672827  381076.35672827  381076.35672827  767001.02148205
  512889.72181163  612736.77731195  346071.31586993  512889.72181163
  251294.00237997  474746.61829186  251294.00237997  512889.72181163
  767001.02148205  621337.07050092 1276169.03703704  474746.61829186
  474746.61829186  808757.4        1450522.94949485  346071.31586993
  474746.61829186  512889.72181163  474746.61829186  381076.35672827
  512889.72181163 1276169.03703704  381076.35672827  381076.35672827
  512889.72181163  474746.61829186  381076.35672827  381076.35672827
  251294.00237997  612736.77731195  346071.31586993  251294.00237997
  989791.38709677  512889.72181163  767001.02148205  474746.61829186
  512889.72181163  621337.07050092  381076.35672827  612736.77731195
  474746.61829186  512889.72181163  474746.61829186  474746.61829186
  474746.61829186  474746.61829186  474746.61829186 1276169.03703704
  474746.61829186  767001.02148205  474746.61829186 1276169.03703704
  381076.35672827  612736.77731195  381076.35672827  512889.72181163
  767001.02148205  381076.35672827  512889.72181163  251294.00237997
  381076.35672827  767001.02148205  381076.35672827  612736.77731195
  346071.31586993  454466.66666667  346071.31586993  512889.72181163
  621337.07050092 1276169.03703704  381076.35672827  251294.00237997
  989791.38709677  767001.02148205  474746.61829186  989791.38709677
  989791.38709677  474746.61829186  512889.72181163  346071.31586993
  612736.77731195  801462.51851852  512889.72181163 1276169.03703704
  381076.35672827  381076.35672827  306322.66666667  474746.61829186
  767001.02148205  512889.72181163  381076.35672827  474746.61829186
  612736.77731195  474746.61829186  512889.72181163  251294.00237997
  512889.72181163  512889.72181163  381076.35672827  474746.61829186
  346071.31586993  474746.61829186  474746.61829186  381076.35672827
  251294.00237997  381076.35672827  767001.02148205  381076.35672827
  949681.28        512889.72181163  512889.72181163  346071.31586993
  512889.72181163  767001.02148205  381076.35672827  474746.61829186
  474746.61829186  381076.35672827  381076.35672827  512889.72181163
  512889.72181163  381076.35672827  808757.4         512889.72181163
  381076.35672827  381076.35672827  346071.31586993  381076.35672827
  474746.61829186  346071.31586993  381076.35672827  474746.61829186
  767001.02148205  512889.72181163  512889.72181163  381076.35672827
  767001.02148205  612736.77731195  381076.35672827  381076.35672827
 1450522.94949485  474746.61829186  251294.00237997  767001.02148205
  474746.61829186  808757.4         512889.72181163  381076.35672827
  767001.02148205  251294.00237997  474746.61829186  381076.35672827
  381076.35672827  381076.35672827  621337.07050092  767001.02148205
  381076.35672827  612736.77731195  381076.35672827  346071.31586993
  381076.35672827  251294.00237997  381076.35672827  767001.02148205
  381076.35672827  346071.31586993  474746.61829186  512889.72181163
  612736.77731195  612736.77731195  512889.72181163  346071.31586993
  512889.72181163  474746.61829186  474746.61829186  381076.35672827
  767001.02148205  767001.02148205  346071.31586993  381076.35672827
  808757.4         808757.4         512889.72181163  767001.02148205
  346071.31586993  381076.35672827  474746.61829186  381076.35672827
  474746.61829186  612736.77731195  767001.02148205  808757.4
  474746.61829186  512889.72181163  381076.35672827  381076.35672827
  381076.35672827  474746.61829186  808757.4         381076.35672827
  381076.35672827  381076.35672827 1276169.03703704  381076.35672827
  346071.31586993  767001.02148205  474746.61829186  989791.38709677
 1276169.03703704  621337.07050092  612736.77731195 1831465.125
  512889.72181163  512889.72181163  767001.02148205  381076.35672827
  346071.31586993  381076.35672827  381076.35672827  474746.61829186
  474746.61829186  767001.02148205  621337.07050092  612736.77731195
  251294.00237997 1276169.03703704 1276169.03703704  381076.35672827
  767001.02148205  346071.31586993  381076.35672827  381076.35672827
  474746.61829186  767001.02148205  474746.61829186  767001.02148205
  949681.28        512889.72181163  474746.61829186  474746.61829186
  474746.61829186 1276169.03703704  381076.35672827  808757.4
  474746.61829186  346071.31586993  474746.61829186  381076.35672827
  512889.72181163  767001.02148205  474746.61829186  612736.77731195
 1831465.125       381076.35672827  474746.61829186  949681.28
  346071.31586993  767001.02148205  512889.72181163  474746.61829186
  474746.61829186  381076.35672827  512889.72181163  381076.35672827
 1276169.03703704  381076.35672827  381076.35672827  381076.35672827
  381076.35672827  346071.31586993  251294.00237997  808757.4
  512889.72181163  381076.35672827  306322.66666667  612736.77731195
  512889.72181163  474746.61829186 1450522.94949485  512889.72181163
  381076.35672827  381076.35672827  474746.61829186  767001.02148205
  381076.35672827  512889.72181163  381076.35672827  474746.61829186
  808757.4         621337.07050092  767001.02148205  949681.28
  612736.77731195  512889.72181163  381076.35672827  808757.4
  621337.07050092  512889.72181163  381076.35672827  381076.35672827
  381076.35672827  989791.38709677  381076.35672827  474746.61829186
  767001.02148205  346071.31586993  381076.35672827  381076.35672827
  346071.31586993  767001.02148205  767001.02148205  474746.61829186
  512889.72181163  381076.35672827  251294.00237997  346071.31586993
  512889.72181163  381076.35672827  989791.38709677  612736.77731195
  474746.61829186  512889.72181163  381076.35672827  251294.00237997
  381076.35672827 1908500.          767001.02148205  512889.72181163
  381076.35672827  474746.61829186  474746.61829186  381076.35672827
  474746.61829186  381076.35672827  346071.31586993  808757.4
  474746.61829186  381076.35672827  381076.35672827  474746.61829186
  684928.57142857  474746.61829186  474746.61829186  767001.02148205
  381076.35672827  381076.35672827  381076.35672827  381076.35672827
  767001.02148205  251294.00237997  381076.35672827  381076.35672827
  767001.02148205  808757.4         767001.02148205  381076.35672827
  474746.61829186  612736.77731195  512889.72181163  381076.35672827
  474746.61829186  381076.35672827  381076.35672827  512889.72181163
  621337.07050092  474746.61829186  474746.61829186  381076.35672827
  251294.00237997  612736.77731195  251294.00237997  474746.61829186
  381076.35672827  381076.35672827  474746.61829186  474746.61829186
  381076.35672827  512889.72181163  512889.72181163  381076.35672827
  381076.35672827  381076.35672827  767001.02148205  801462.51851852
  512889.72181163  767001.02148205  381076.35672827  381076.35672827
  381076.35672827  474746.61829186  381076.35672827  989791.38709677
  989791.38709677  381076.35672827  767001.02148205  989791.38709677
  381076.35672827  474746.61829186  346071.31586993  474746.61829186
  381076.35672827 1450522.94949485  989791.38709677  381076.35672827
  346071.31586993  474746.61829186  474746.61829186  381076.35672827
  346071.31586993  474746.61829186  512889.72181163  251294.00237997
 1276169.03703704  381076.35672827  767001.02148205  767001.02148205
  512889.72181163  251294.00237997  474746.61829186 1450522.94949485
  381076.35672827  474746.61829186  612736.77731195  512889.72181163
  512889.72181163  381076.35672827  512889.72181163  474746.61829186
  767001.02148205  474746.61829186 3800000.          767001.02148205
  767001.02148205  512889.72181163  381076.35672827  767001.02148205
  381076.35672827  512889.72181163  474746.61829186  346071.31586993
  474746.61829186  346071.31586993  381076.35672827  621337.07050092
  346071.31586993  808757.4         381076.35672827  381076.35672827
  251294.00237997  381076.35672827  381076.35672827  381076.35672827
  767001.02148205  474746.61829186  767001.02148205  808757.4
  251294.00237997  381076.35672827  454466.66666667  474746.61829186
  381076.35672827  512889.72181163  474746.61829186  474746.61829186
  474746.61829186  474746.61829186  808757.4         767001.02148205
  767001.02148205  381076.35672827  381076.35672827  381076.35672827
  767001.02148205  989791.38709677  251294.00237997  381076.35672827
  381076.35672827 1831465.125       474746.61829186  474746.61829186
  474746.61829186  512889.72181163  251294.00237997  474746.61829186
  767001.02148205  346071.31586993  381076.35672827  346071.31586993
  381076.35672827  474746.61829186 1450522.94949485  808757.4
  381076.35672827  512889.72181163  767001.02148205  251294.00237997
  512889.72181163 1276169.03703704  989791.38709677  512889.72181163
  512889.72181163  512889.72181163  346071.31586993  474746.61829186
  381076.35672827  801462.51851852  346071.31586993  512889.72181163
  808757.4         474746.61829186  767001.02148205  251294.00237997
  346071.31586993  381076.35672827  949681.28        808757.4
  346071.31586993  767001.02148205  767001.02148205  808757.4
  512889.72181163  381076.35672827  612736.77731195  474746.61829186
  346071.31586993  474746.61829186  474746.61829186  251294.00237997
 1276169.03703704 1276169.03703704  251294.00237997  346071.31586993
  512889.72181163  767001.02148205  512889.72181163  381076.35672827
  381076.35672827  381076.35672827  612736.77731195  381076.35672827
 1276169.03703704  251294.00237997  381076.35672827  612736.77731195
  512889.72181163  251294.00237997  612736.77731195  808757.4
  989791.38709677  512889.72181163  381076.35672827  474746.61829186
  381076.35672827  381076.35672827  474746.61829186  381076.35672827
  381076.35672827  381076.35672827  381076.35672827  767001.02148205
  474746.61829186  474746.61829186  767001.02148205  512889.72181163
  474746.61829186  474746.61829186  621337.07050092  512889.72181163
  346071.31586993  989791.38709677  381076.35672827  808757.4
  381076.35672827  346071.31586993  251294.00237997  381076.35672827
  251294.00237997  346071.31586993  512889.72181163  512889.72181163
  512889.72181163  474746.61829186  346071.31586993  381076.35672827
  251294.00237997  474746.61829186  474746.61829186  612736.77731195
 2360970.          989791.38709677  381076.35672827  251294.00237997
  381076.35672827  306322.66666667  381076.35672827  346071.31586993
  767001.02148205  381076.35672827  381076.35672827  381076.35672827
  512889.72181163  512889.72181163  346071.31586993  767001.02148205
  621337.07050092  381076.35672827  381076.35672827 1276169.03703704
  381076.35672827  346071.31586993  612736.77731195  612736.77731195
  474746.61829186  767001.02148205  381076.35672827  949681.28
  612736.77731195  346071.31586993  346071.31586993  381076.35672827
  767001.02148205  474746.61829186 1276169.03703704  512889.72181163
  381076.35672827  767001.02148205  474746.61829186  381076.35672827
  512889.72181163  989791.38709677  381076.35672827  474746.61829186
  381076.35672827  251294.00237997  612736.77731195  346071.31586993
  346071.31586993  612736.77731195  381076.35672827  381076.35672827
  381076.35672827  381076.35672827  251294.00237997  251294.00237997
  767001.02148205  346071.31586993  346071.31586993  381076.35672827
  381076.35672827  512889.72181163 1276169.03703704  474746.61829186
  767001.02148205  808757.4         381076.35672827  251294.00237997
  251294.00237997  381076.35672827  381076.35672827  612736.77731195
  381076.35672827  381076.35672827  612736.77731195  474746.61829186
  989791.38709677  381076.35672827  381076.35672827  381076.35672827
  612736.77731195 1831465.125       381076.35672827  381076.35672827
 1450522.94949485  767001.02148205  381076.35672827  808757.4
  612736.77731195  767001.02148205  381076.35672827  767001.02148205
  381076.35672827  381076.35672827  767001.02148205  251294.00237997
  612736.77731195  621337.07050092  684928.57142857  381076.35672827
  346071.31586993  474746.61829186  512889.72181163  474746.61829186
  474746.61829186  767001.02148205  621337.07050092  346071.31586993
  381076.35672827  612736.77731195  381076.35672827  989791.38709677
  381076.35672827  346071.31586993  612736.77731195  381076.35672827
  767001.02148205  381076.35672827  381076.35672827  381076.35672827
  381076.35672827  381076.35672827  381076.35672827  512889.72181163
  251294.00237997  989791.38709677  767001.02148205  474746.61829186
  474746.61829186  381076.35672827  808757.4         512889.72181163
  251294.00237997  684928.57142857  808757.4         512889.72181163
  381076.35672827  767001.02148205  381076.35672827  474746.61829186
  474746.61829186  251294.00237997  381076.35672827  767001.02148205
  989791.38709677  808757.4         612736.77731195  474746.61829186
  381076.35672827  767001.02148205 1276169.03703704 1276169.03703704
  381076.35672827  512889.72181163  474746.61829186  474746.61829186
  346071.31586993  381076.35672827  612736.77731195  512889.72181163
  381076.35672827  381076.35672827  474746.61829186  767001.02148205
  381076.35672827  381076.35672827  346071.31586993  381076.35672827
  381076.35672827  381076.35672827  381076.35672827  474746.61829186
  474746.61829186  512889.72181163  474746.61829186  989791.38709677
  381076.35672827  346071.31586993  251294.00237997  612736.77731195
  512889.72181163  381076.35672827  381076.35672827  512889.72181163
  767001.02148205  612736.77731195  996050.          346071.31586993
  621337.07050092  474746.61829186  512889.72181163 1276169.03703704
  474746.61829186  512889.72181163  474746.61829186  512889.72181163
  474746.61829186  474746.61829186  251294.00237997  612736.77731195
  767001.02148205  767001.02148205  381076.35672827  621337.07050092
  474746.61829186  621337.07050092  474746.61829186  612736.77731195
  474746.61829186  346071.31586993  474746.61829186  474746.61829186
  512889.72181163  767001.02148205  251294.00237997  612736.77731195
  346071.31586993  512889.72181163  612736.77731195  512889.72181163
  474746.61829186  381076.35672827  381076.35672827  381076.35672827
  474746.61829186  474746.61829186  474746.61829186  612736.77731195
  612736.77731195  767001.02148205  512889.72181163  808757.4       ]

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error, r2_score

print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE: ",mean_squared_error(y_test,y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 169669.82287822402
MSE:  120290233035.21863
R2 Score: 0.33103682984815497

#random forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
x_train

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
3497,4.0,2.50,2990,16809,2.0,0,0,3,2990,0,1990,2009
1694,4.0,1.50,1840,4337,2.0,0,0,4,1840,0,1917,0
4486,2.0,1.00,1100,8281,1.0,0,0,4,1100,0,1947,1988
1082,3.0,2.50,2720,6014,2.0,0,0,3,2720,0,2002,0
2882,4.0,1.75,1290,3060,2.0,0,0,4,1290,0,1906,1990
...,...,...,...,...,...,...,...,...,...,...,...,...
2243,5.0,3.25,2750,7500,2.0,0,1,3,2150,600,1937,1997
131,3.0,2.00,1550,15040,1.0,0,0,4,1550,0,1958,1972
2302,3.0,1.75,1520,15090,1.0,0,0,4,1520,0,1968,0
4526,2.0,1.00,2550,21675,1.0,0,1,4,1610,940,1958,1972
3755,3.0,2.75,2090,9620,1.0,0,0,3,1340,750,1987,2000

In [ ]:
rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

In [ ]:
rf_model.fit(x_train, y_train)

print("Model trained successfully!")

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Model trained successfully!

In [ ]:
y_pred = rf_model.predict(x_test)

print(y_pred)

[ 636960.06        473611.985       563922.15        286631.68958333
  568003.63565217  499890.84        376067.5         405908.93105769
 1178766.48        370323.9335348   706726.8125      728446.74
  816510.24555554  325329.11857143  918637.81        434916.14318182
  474044.22857143  925352.7         507653.622       415553.
  196150.34        279469.02        426819.08        608642.73333333
  567056.32        529505.01        633907.5325      484702.74
  795212.23333334  270570.          548062.04833334  354350.3
  720744.04        553418.79999999  217730.55       1286537.96
 1093045.          354853.24166666  738156.50999999  593129.08086953
  385907.53428572  381709.99000001  275408.57428572  234229.34666666
  635161.59857142  389814.5         552265.16666666  787679.53857142
  508937.          466352.8822222   531748.85333334  515134.05333334
  244397.38533333  257247.625       555313.57888886  227877.57
  333998.05380951  561212.3547619   552479.00130434  415638.87999999
  575565.09416667  513866.22        513005.54373016  891203.08333333
  767439.89        445170.16999999  486568.1475      269642.80333333
  410213.5         743681.22        258524.5         521426.88097821
  355248.37208333  437280.38        512817.26571429  414458.11992063
  487933.88782609  468947.72436507  308505.60714286  369935.95
  453198.56318181  643955.58875     388720.38666667  577273.0175442
  365665.55555556  486337.19        412348.29428571  545470.39285714
  450803.68785716  917294.52        430016.34428571  403886.87285715
  414145.25        602003.91666667  592899.5         522599.52222224
  355151.04857143  419540.7         551170.30333333  575106.77695651
  585884.08        441480.          433983.79083333  465283.06416667
  335188.38        378395.65357143 1016440.59325398  383441.5
  406258.7         522111.24047619  404132.07000004  587429.015625
  659755.56        353429.15333333  298822.32582609 1223226.74
  682418.9         280074.33333333  608994.         2834373.02
  251155.08333333  373956.18375    1065398.14999999  525876.97333332
  414313.63        877153.26        317528.7225     1205772.92
  511577.37999998  341923.69047619  720969.32        346517.37589286
 1161122.44        685688.5         399065.24375     473924.46666667
 1041200.25        648372.7         378079.21875    1212821.81
 1406088.2         396807.75        347189.51666666  414520.70238096
 1062718.84        791624.83333333  593690.29833336  569687.1
  392981.86        901186.52       1147535.95        261763.81666666
  603783.14565216  220405.17        398047.47776515  481982.71
  257941.85833333  357128.11904762  226550.18333333  338613.4
  370503.405      1256642.01        375792.86142858  383737.07282609
  231247.795       360679.34874999  388442.165       434168.74333334
  393897.51111112  533719.31565217  287847.43        389572.50571429
  477094.99        636240.94526979  571647.25        417191.42857143
  548251.89846155  613236.79179487  441136.08        529364.75
  407048.68571429  357947.36541666  329466.97692307  870126.
  548854.12948718  705804.47142857  646832.01        454450.07920635
  262075.35625     290513.69782609 1177892.84        412052.04107146
  289046.758       398256.02380953  441062.93047618  498546.84666667
  408049.81        626433.2         245237.7         353503.95142856
  383030.77        392144.33888889  523339.9         353836.63779762
  650329.84714286  811426.          985054.94333333  293947.38
  393775.83960321  900639.16        703158.14714285 2249749.14
  283689.01388889  614091.9         440342.5         383569.4
  577666.18000002  396007.86714284  507008.37        263383.5
  250427.66666667 1076355.1         615419.68666666  413620.41
  444408.75        466480.69555556  550733.96500005  363676.11
  297136.46        362494.46319443  414855.45416667  451559.96825396
  312833.565      1183546.855       880937.8475      295390.48214286
  563015.355       886365.9065      317449.68444444  672119.87
  401175.62        395036.74738095  600512.39428571  323994.62
  837290.03923077  835849.78        512722.95208333 1274310.93
  749748.84        647915.665       405168.81555556  346529.22857143
  405305.63309523  282863.97714286  378443.44       1046165.58142857
  304342.32       1121961.5         540755.55        353826.85999999
  385418.03636364  238302.86       1042446.2         483087.56231885
  439945.86        707509.95857142  889037.46        658863.23
 1221120.89        761421.48999999  499032.63        843032.60666666
  455871.65904761  461179.3666666   439850.115       383217.41555553
  648615.36        352866.71375     461286.54111108  436437.89
 1256933.          456401.          381072.375       515929.63714286
 3281949.6         652383.82        368586.6         723054.0675
  340203.9         328544.98279504  267567.10714286  404258.37857144
  452559.00833334  406217.36952381  260842.403       411912.87999999
  506494.24714286  610945.35333333  458528.5         931956.79
  467856.10833334  510755.71928571  404476.32428574  508885.23
  465093.90625     654621.59        418805.28714286 1445736.69
  311199.45666666  589525.4         682488.85714285  923606.66142857
  338570.61875     516226.58        495804.27285714  438340.79
  370144.22333334  376636.13564104  380684.7375      456205.91928571
  504177.5         985138.          441204.89555556  688092.
  520577.41904761  295216.4320833   422548.59071428 1097565.
  416644.97        603401.33555556  467381.92333333  635058.43285714
  589885.5         653122.874       346781.45999999  369529.70714286
  434827.92384612  315097.40666666  862817.96        436176.99111108
  590577.31166667  274463.92857143  412029.65708333  474662.625
  298168.70333332  430948.81333333  309472.33126985  544709.71249999
  481710.67333335  500108.51666665 1125149.49        623690.52857142
 1800528.16666666 1855029.9         511219.4133333   202643.45
  413980.31999999  886866.          513811.31785713  335905.5
  508593.15541667  508312.76        361784.99        522806.84000001
  599926.          324932.61111112  425376.78571429  429242.57333333
  865974.74        209400.12        322974.22004831  383022.35888889
  549848.93307692  614877.66        549152.89583334  443590.53
  577462.81333333  363270.06        678651.95886364  404268.19535713
  263169.39256409  527342.4         248144.3         818319.21
  496658.5         232422.61128204  451489.93666667  316127.725
  625945.77755556  645714.57142857  841471.175       585505.74
  692330.62        480418.91857142  369268.5         761274.
  836755.75        523509.5         656853.74603178  390286.77
  596449.29714281  361064.90333333  408054.55555556  980412.51923077
  389924.12        284517.          410233.8773077   407296.95589286
  479496.2         542172.54        712371.97989011  383461.75
 1067219.82        591524.32343756 1417140.5         502367.30289851
  632188.25        798391.51        765674.38        481311.31142857
  527681.575       685786.60555556  423931.36        655057.6
  450589.68285715  225715.0415     1020467.33333333  657350.374
  232467.63666664  534108.52        585061.67        306171.06888889
  229389.07564102  574537.9366666   507895.66777778  356436.235
  352529.22857141  459571.61        379693.          781078.72444444
  394475.37142857  368423.69047619  622990.98        343698.28
  602989.64565219  348097.35571429  556046.88166667  568526.77963766
  652279.68        411217.36       1738642.31        642456.45
  423043.76857143  417176.61666674  250611.5        1008099.74333333
  932700.18857142  450898.33333333  436846.01000003  402305.71333333
  259008.14       1572097.21        355936.57730769  408233.
  463816.76666667  716302.92198864  477279.94782604  326203.91875
  658828.05        661660.5         435139.20833334  473092.78666667
  514499.375       318752.6157143   384926.80740261  907975.32589744
  282617.5         599524.56666666  575050.3         484985.4
  466370.82        447012.66666667  336019.29        508487.71333333
  608378.07142857  287931.41        340720.29333333  389858.04500002
  272154.63999999  548934.67555556  437352.98666667  687784.49
  572069.71666667  488632.85714282  318911.665       572958.
  421910.46380956  382020.83333333  470055.5         389221.67142858
  552387.69666667  540279.8575      871374.96        503228.17666667
  483385.72666667  603881.06       1076133.07333333  435828.05714286
  239627.85794871  473494.26        907593.99        566552.525
  621607.5         498719.11428569  962616.95        735525.5
  343488.87714286  430090.85714286  979302.73        771812.04
  277097.86619659  521391.52        585490.82        679870.3865
  330842.02500001  793152.80333333  350314.436       736942.02
  623186.19999999  839920.25       1288787.81        239884.75208333
  505996.29        564344.54285714  404575.6075      414551.98
  381641.37999999  585461.71666666  355568.88333333  432738.02
  291012.82673076  512301.94        206408.29782609  388134.87809524
  548905.3033333   453123.46333333  503577.9356044   298228.93286325
  505214.27857143  258350.          273850.16666666  389035.375
  641384.52        607896.54333333  582158.23231883  607053.46666668
  384216.375       536909.22875     338701.6         499932.32666667
  775040.6675      584054.8333333   311682.          744704.42333333
  413212.67        485816.68        536632.95666664  206029.04166665
  483201.38        827211.95        481460.1325      360693.2902381
  565412.38692308 1177573.5         966436.9         443426.03428571
  651856.1578125   689487.66714286 1262055.94        572254.68
  558164.525       593570.45555556  312457.          552849.63333333
  347251.83888889  637970.91        492658.13111112  683930.96695971
  452242.78        502139.26        534263.22500001  686425.66
  490422.8125      448389.06404762  568027.64565217  529478.12
  300399.03        691597.67        736951.18       1101401.25
  596524.8         641674.14333333  543765.65        601483.38695651
  588077.79565217  725916.5         339322.635       473459.68
  250597.58166666  736539.62        452374.18448718  952481.11923077
  450815.50000004 1116221.79        511959.44666667  357663.75428572
  910066.91       1068996.31        620258.02333337  480937.58555556
  319213.18966665  417004.28671498  692231.82666669  437534.31
  701219.          396904.4461905   611220.91        336658.73305554
  279222.03230769  434212.97833333  472445.28958333 1222967.72
  751910.         1232660.71        338987.91875     770104.83333333
  266667.86153845  613590.69        737828.65428571  517504.36833333
  313129.9         465792.69666665  337019.353658    508199.3625
  918884.5         769984.3675      368041.2         253917.3333333
  485476.2299999   458975.04        280086.38333333  460090.24166666
  589055.40000001 1381338.38        299177.34285715  395970.03
  371512.03333333  321897.02361111 1180516.46        433348.89
  332183.79619048  590439.53846154  335409.5         270018.35714286
 1034666.71        471928.66        414731.11946429  449472.46666664
  409541.05454546  636388.55313718  452745.59821429  351310.91
  345785.28571429  775799.58        380618.61309524 1122754.
  449320.38333334  763036.15666666  928602.48065934  578295.37666667
  496817.46        324511.48333333 1676833.28        315828.36214285
  580630.31        764241.57673077  222571.56        412975.09499997
  307854.79        294160.37        405292.83333333  767666.625
  455213.5714286   388767.44695654  433468.00833333  179070.15496895
  481162.          529340.90071428  496251.64666668 1314636.71
  458958.52222223  304459.14285715  555040.82        786992.07
  370624.90888889  391863.93571429  383067.5         700389.58333333
  417700.62714285  406859.83333334  283306.06714286  303528.21380953
  305702.03333333  485034.71333334  399542.12660714  440720.79
  222459.09        509164.36571429  384767.56666667 1046959.49
  830067.53        446638.93282052  703689.          303483.5
  610251.2133332   361618.42666666  617397.66166667  409738.06777778
  427568.20875     771852.785       333332.64285715  466704.96
  449875.125       530046.8554762   286474.93749998  678148.29166667
  279118.5        1080776.9         637405.05333333  423476.43333333
  353979.62416667  574763.91999999  327497.          401751.96928572
 1131520.16       1189775.          490342.25        267142.74666666
  844325.64285713  291988.168       460524.23333333 1504098.71
  347578.83        458689.5         799522.2         463256.90904761
  468372.57       1112939.06        471122.          621649.937
  321982.65666667  291702.53541666 1047658.65428571  414723.71875
 1061003.26        317196.11333333  389082.08       1213217.87
 4258995.72333333  435893.21142856  423522.11214286  792735.34
  245118.9         431603.56        297366.59897432  384039.39166666
  235965.248       758308.25        637949.14666668  523140.
  363990.55        476735.38738095 2494110.38        306702.24782609
  320732.11        953596.55        994847.63333333  428401.
  479775.31       1226495.41        246580.43961538  188055.385
  256745.52714286  295607.68875     293723.82499999  339201.5
  928595.69999999 1259189.32        518839.77956519  361939.83333334
  671003.38        578903.97666665  378789.86428571  441384.60208333
  327786.40666667  389627.99818182  547014.78        673584.35636364
  483475.86        440557.05873016  361528.5         401642.84398552
  294183.7099379   423023.84347828  349549.58285713  473605.5
  441160.54615384  342486.78499998 1134276.91        716676.325
  257313.42222222  500876.06        305737.20142858  527258.77282052
  408441.61428572  378833.80666666  511435.14        358652.
  411494.07777779  440210.98142852 1025148.75        432182.81
  333245.5         436594.06571429  811152.61142857  393423.89230769
  450000.28        283254.83333333  407848.36666666  403458.19782609
  613825.23        390543.24        417404.33333334  406877.07208333
  447627.55        517639.425       415750.78857142  592908.24208333
 1192324.56231883  598554.7         534556.93333332 1138157.21
  426503.39714286  448508.69722945  208637.44666655  644617.34
  505334.17857138  415814.4973077   216931.26666667  360601.12053571
  572585.687       520009.69326085  449591.7075     1055189.69
  397865.40476188  989300.          281259.76190475  337153.
  733054.21        504131.74333331  279372.68482143  531717.27
  386241.29555556  386617.99        280832.32446429  453188.62
  607834.77428568  963752.5        1126765.16        736080.
  336199.          642645.54428571  506025.5         442402.39714286
  280035.173       493089.12857142  492217.34        535985.25248445
  453141.65        279399.7         463222.75        806694.88
  596304.5         339253.5         503791.20666668  434127.28999997
  667188.33333333  611980.80952381 1033329.48       1096917.5
  477241.20722222  511841.01964286  288022.52732143  915583.5
  460577.125      1815889.          479983.00565217  516906.6175
  321307.9         661683.75        641173.78        785928.
  533192.57222222  617818.41666667  785949.77777777  445231.455
  417490.76666667  460552.63        502217.15857144  580169.68055556]

In [ ]:

print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE: ",mean_squared_error(y_test,y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 169669.82287822402
MSE:  120290233035.21863
R2 Score: 0.33103682984815497