In [3]:
import joblib

In [4]:
a=joblib.load('Linear.pkl')

In [5]:
a.predict([[100]]) #[]->series,[[]]=dataframe

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[227.09357319]])

Big Data-large dataset
(massive) data

#Practice question

In [6]:
import pandas as pd
df=pd.read_csv('data.csv')

In [7]:
df.head(5)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [8]:
x=df[['bedrooms','bathrooms','sqft_living','sqft_lot','floors','waterfront','view','condition','sqft_above','sqft_basement','yr_built','yr_renovated']]
y=df[['price']]

In [9]:
df.isnull().any()

date             False
price            False
bedrooms         False
bathrooms        False
sqft_living      False
sqft_lot         False
floors           False
waterfront       False
view             False
condition        False
sqft_above       False
sqft_basement    False
yr_built         False
yr_renovated     False
street           False
city             False
statezip         False
country          False
dtype: bool

In [10]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [14]:
x_train

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
4523,3.0,4.50,5230,17826,2.0,1,4,3,3740,1490,2005,0
3879,4.0,2.50,1540,1870,2.0,0,0,3,1540,0,2014,0
685,4.0,2.00,1630,9010,1.0,0,0,4,1050,580,1975,0
3737,3.0,2.50,2010,7200,2.0,0,0,3,2010,0,1994,0
1537,3.0,1.50,1270,11600,1.0,0,0,4,1270,0,1964,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1524,4.0,1.00,1600,4300,1.5,0,0,4,1600,0,1916,0
4212,3.0,1.75,1770,29004,1.0,0,0,3,1770,0,1959,1989
1430,4.0,2.75,2020,2750,1.0,0,0,3,1010,1010,1917,2014
3003,4.0,2.00,2120,11479,1.0,0,0,4,1060,1060,1940,2001
3048,6.0,3.00,2180,7956,2.0,0,0,3,2180,0,1980,0

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
model=LinearRegression()

In [17]:
model.fit(x_train,y_train)

LinearRegression()

In [18]:
y_pred=model.predict(x_test)

In [19]:
model.predict(x_test)

array([[ 435773.98698144],
       [ 698777.39107719],
       [ 990758.14937985],
       [ 875186.98653989],
       [ 483560.37856381],
       [ 830859.60900011],
       [ 562670.37667734],
       [ 574569.785322  ],
       [ 291968.64035328],
       [ 700716.63708436],
       [ 455899.5260522 ],
       [ 506916.43150812],
       [ 650406.04553632],
       [ 278847.73899714],
       [ 839483.48923751],
       [ 260919.38336892],
       [ 247906.64828047],
       [ 292463.54129421],
       [ 440748.43612379],
       [ 408585.25844732],
       [ 627246.22730216],
       [ 598984.85488315],
       [ 345436.63738044],
       [ 398173.98460147],
       [ 391285.53882139],
       [ 452599.80102799],
       [1014198.18302261],
       [ 415462.60477484],
       [ 673460.63631946],
       [ 461060.08607169],
       [ 431395.28944335],
       [ 367082.01166382],
       [ 677447.32393445],
       [1231873.3598804 ],
       [ 400541.42111435],
       [ 304764.62707965],
       [ 303072.17641521],
       [ 629253.63937791],
       [ 670227.16695656],
       [ 730433.52008954],
       [ 376996.78433882],
       [ 828387.5369709 ],
       [1016967.97491324],
       [ 526360.47635151],
       [ 440478.71453708],
       [ 633633.28640128],
       [ 356539.80551773],
       [ 382893.8015806 ],
       [ 951654.61351302],
       [ 358227.92883396],
       [ 325373.23569856],
       [ 299902.72810938],
       [ 418350.70571977],
       [ 674581.20621841],
       [ 711256.08122939],
       [ 414010.92984333],
       [ 959155.20733913],
       [ 351302.75891243],
       [ 267659.55784908],
       [ 361194.11566271],
       [ 589712.87686662],
       [ 369691.26157165],
       [ 714286.55228837],
       [ 518573.77657038],
       [ 717140.34445595],
       [1122786.34623165],
       [ 689060.50873771],
       [ 313057.24836662],
       [ 310283.87705102],
       [ 504475.46647375],
       [ 362542.57598167],
       [ 165378.1741116 ],
       [ 929402.47712769],
       [ 363806.30632036],
       [1293767.27093318],
       [ 478458.66238753],
       [ 450164.54213549],
       [ 323845.62328968],
       [ 416919.66314188],
       [ 316710.0869699 ],
       [ 548526.65582252],
       [ 980990.11850876],
       [ 476747.03107233],
       [ 307410.58536339],
       [ 745920.12232903],
       [ 536245.19915746],
       [ 532792.35340674],
       [ 496729.08463031],
       [ 596481.01953625],
       [ 842709.6492246 ],
       [ 284573.73273434],
       [1157716.53791186],
       [ 440214.7755553 ],
       [ 619951.29990361],
       [ 996812.99676979],
       [ 469238.19921401],
       [ 515683.87543802],
       [ 652625.65484402],
       [ 375092.42966216],
       [ 517553.78761322],
       [ 335356.93155187],
       [ 191497.84732563],
       [ 668977.7791325 ],
       [ 245525.24854799],
       [ 736983.11421459],
       [ 707375.42173837],
       [ 369687.89324133],
       [ 819518.11974214],
       [ 339550.53460514],
       [ 283758.80408108],
       [ 357453.36791347],
       [ 398848.50444711],
       [ 539279.7386178 ],
       [ 321750.86073602],
       [ 483735.56377293],
       [ 981919.35206889],
       [ 368061.73692098],
       [ 271053.96025707],
       [ 279515.5201581 ],
       [ 621432.4338021 ],
       [ 327302.10785035],
       [ 553271.12030365],
       [ 526752.89249513],
       [ 470629.5860736 ],
       [ 720853.95842912],
       [ 690381.21777142],
       [ 298309.50818627],
       [ 733025.90898121],
       [ 562335.82753606],
       [ 521158.58346135],
       [ 690022.0074451 ],
       [ 429883.17984556],
       [ 748085.67561298],
       [1037558.16336317],
       [ 992386.88646031],
       [ 533846.34908269],
       [ 683924.27628717],
       [ 476002.94646742],
       [ 603811.4695977 ],
       [ 436561.48924345],
       [ 418018.00528466],
       [ 479215.30568022],
       [ 325994.78812486],
       [ 272725.80451434],
       [ 315121.6813945 ],
       [ 302156.33562722],
       [ 596015.70303422],
       [ 414472.47412556],
       [1047340.03137522],
       [ 529262.29857444],
       [1219167.62504699],
       [ 622692.17773654],
       [ 575681.48896122],
       [ 460748.8766512 ],
       [ 196330.40650043],
       [ 208926.68501838],
       [ 417525.80941752],
       [ 677096.87235717],
       [ 579588.2133909 ],
       [ 439631.4353772 ],
       [ 459125.33281052],
       [ 359414.9415766 ],
       [ 538840.95944044],
       [ 638458.7682436 ],
       [ 491553.57209485],
       [ 273750.02137188],
       [ 467238.09442841],
       [ 546267.61510534],
       [ 817229.97109498],
       [ 575584.1195784 ],
       [ 422412.62239122],
       [ 333563.11739892],
       [ 354736.34996608],
       [ 488220.1049743 ],
       [ 366294.65209083],
       [ 346836.9764445 ],
       [ 455284.44743564],
       [ 465639.82607532],
       [ 267137.01310415],
       [ 400684.63333686],
       [1003729.92211731],
       [ 597036.26361834],
       [ 689253.80399357],
       [1381408.9679592 ],
       [ 710090.04892539],
       [ 464279.14238333],
       [ 362028.02190283],
       [ 869340.11374387],
       [2094354.77462981],
       [ 480374.53900498],
       [1515991.20426547],
       [ 820891.78360396],
       [ 475946.37797549],
       [ 680062.28571109],
       [ 449238.85397886],
       [1881472.33407967],
       [ 542938.61448795],
       [ 550983.14799904],
       [ 600383.90090655],
       [ 451742.40754058],
       [ 339039.58680851],
       [ 621193.97371961],
       [ 328974.8635193 ],
       [ 554024.30144988],
       [ 478438.87597998],
       [ 398332.7976489 ],
       [ 368093.6243966 ],
       [ 738787.46091873],
       [ 287284.45695129],
       [ 434471.74802482],
       [ 334212.14813321],
       [ 421833.33535018],
       [ 657440.37372616],
       [2454826.8369557 ],
       [ 390524.29490426],
       [ 248858.57033099],
       [ 267794.54052048],
       [ 533899.51950336],
       [ 537425.60740108],
       [ 674857.02110496],
       [ 477485.76170084],
       [ 279087.76407393],
       [ 299937.83290373],
       [ 572488.97384357],
       [ 438385.35055703],
       [ 406761.3511229 ],
       [ 751031.49132844],
       [ 309767.65245789],
       [ 514875.35216362],
       [ 406127.64182554],
       [ 754530.3315774 ],
       [ 538208.12583637],
       [ 420408.18566215],
       [ 330582.37612094],
       [ 902364.91306495],
       [ 337227.1564514 ],
       [ 844950.40321784],
       [ 666093.45235052],
       [ 439305.5395848 ],
       [ 435839.14137973],
       [ 401647.59174559],
       [ 514008.91029003],
       [ 220250.64208539],
       [ 471396.90928277],
       [ 731306.94868314],
       [1381478.22976544],
       [ 308341.73731016],
       [1175114.95832296],
       [ 804502.05665833],
       [ 814254.1092713 ],
       [1090365.30465815],
       [ 987891.58522341],
       [ 396865.4917842 ],
       [1304893.90241105],
       [ 321565.57723127],
       [ 627687.23699037],
       [ 672235.18420481],
       [ 492916.27123228],
       [ 839708.76601933],
       [ 233682.70280937],
       [ 292221.6589315 ],
       [ 417489.11096542],
       [ 300153.14790943],
       [ 604134.17438101],
       [ 584686.15738523],
       [ 431446.54685046],
       [ 260181.32651778],
       [ 299850.48873912],
       [ 580138.61067807],
       [ 701945.03529567],
       [1405045.65018217],
       [ 560987.60411981],
       [ 345390.38207475],
       [ 399512.96316679],
       [ 422345.02893818],
       [1324232.15558746],
       [ 740738.08008469],
       [ 802825.74961849],
       [ 508867.65376034],
       [ 702760.90600446],
       [ 410721.69175347],
       [ 271794.72900456],
       [ 768860.75074007],
       [ 568683.28645515],
       [1301414.53863781],
       [ 804191.34862602],
       [ 427381.54486116],
       [ 382997.32994184],
       [ 209910.75951919],
       [ 905657.82140546],
       [ 870644.39123047],
       [ 934968.42373157],
       [ 336111.86110007],
       [ 379678.08423711],
       [ 319376.43813549],
       [ 497622.60279273],
       [ 593695.31517908],
       [ 523552.14709186],
       [ 563610.33800372],
       [ 730263.01985363],
       [ 669237.4324249 ],
       [ 251269.01199034],
       [ 280830.05986127],
       [ 655588.33618602],
       [ 459140.0920137 ],
       [ 845383.06781005],
       [ 707006.73435282],
       [ 541568.56461001],
       [ 333257.05746357],
       [ 555444.47980834],
       [ 560430.37724775],
       [ 418155.28214239],
       [ 529140.39835933],
       [ 504156.24540293],
       [ 556921.88898877],
       [ 333324.73805381],
       [1034280.47884082],
       [ 290810.16883455],
       [ 231153.89467964],
       [ 565101.15903548],
       [ 572312.43777234],
       [ 560073.10009801],
       [ 456263.03937371],
       [ 499482.90263129],
       [ 518715.80981185],
       [ 590773.34419618],
       [ 299719.0115552 ],
       [ 234986.34307925],
       [ 502949.21795631],
       [ 813821.42243526],
       [ 371635.84895936],
       [ 775475.11031624],
       [ 769803.41096167],
       [ 605958.7862558 ],
       [ 762179.42915046],
       [ 591335.89680007],
       [ 234694.3173775 ],
       [ 798755.38232857],
       [ 611421.39871939],
       [1458539.7245011 ],
       [1071544.6825222 ],
       [ 269856.17688755],
       [ 376290.83499015],
       [ 561136.68587516],
       [ 961717.42902264],
       [ 353815.43141534],
       [ 602118.74661158],
       [ 451394.17366469],
       [ 496971.8929856 ],
       [ 278708.47396001],
       [ 377682.93711318],
       [ 669707.79810862],
       [1105097.42640242],
       [ 406824.32341306],
       [ 574035.53303131],
       [ 222975.60597956],
       [ 223503.52272078],
       [ 647431.06222247],
       [1811298.53575747],
       [ 480018.71150471],
       [ 554264.20908351],
       [1351978.30272196],
       [ 398206.80239803],
       [ 676271.98189892],
       [ 646695.75580867],
       [1800411.71579794],
       [ 217903.87885734],
       [ 438744.97979135],
       [ 688803.48928259],
       [ 858305.29608784],
       [ 688790.75229032],
       [ 339907.70217026],
       [ 630636.39292702],
       [ 220310.70746449],
       [ 483608.26998254],
       [ 343743.0734222 ],
       [ 515385.1179047 ],
       [ 356804.65806244],
       [ 469826.9820239 ],
       [ 483135.66335611],
       [ 343041.87753809],
       [ 546653.24174888],
       [ 246042.14774124],
       [ 339143.44563025],
       [ 434445.30522755],
       [1016327.67170726],
       [ 343013.26541814],
       [ 359633.46063538],
       [ 590073.50085217],
       [ 421182.01117944],
       [ 450017.44224077],
       [ 405143.55098204],
       [ 260522.08109934],
       [ 347551.167776  ],
       [ 544473.15273852],
       [ 875818.21843674],
       [ 685067.0817305 ],
       [ 669454.78558909],
       [ 292745.27268353],
       [ 327653.45645969],
       [ 383025.60924087],
       [ 663350.42343453],
       [ 515475.0378079 ],
       [ 653396.64813359],
       [ 428007.49295066],
       [ 340296.3620083 ],
       [ 643329.53587817],
       [ 205144.27116246],
       [ 319893.42407376],
       [ 782886.92509914],
       [ 371076.85803061],
       [ 362412.32697674],
       [ 701992.52605933],
       [ 544777.55816546],
       [ 378757.78344489],
       [ 471881.92246017],
       [ 585235.4775026 ],
       [ 442766.74798832],
       [ 624057.90222063],
       [ 417649.0862168 ],
       [ 325587.94359538],
       [ 392767.49655612],
       [ 489572.17934507],
       [ 593123.76793699],
       [ 456376.70231047],
       [ 438124.1874903 ],
       [ 510626.92764311],
       [ 547923.76195239],
       [ 478870.24908085],
       [ 352123.47226441],
       [ 533586.74654546],
       [ 895635.24266848],
       [ 886132.36789434],
       [ 452739.54283473],
       [ 594240.9130954 ],
       [ 557486.65524416],
       [ 659308.76018826],
       [ 664418.06293129],
       [ 650714.72863677],
       [ 715753.42786643],
       [ 379755.98903833],
       [ 386481.12960289],
       [ 496726.77806372],
       [ 701421.32442191],
       [ 422948.35043244],
       [ 867896.20370277],
       [ 903987.09032448],
       [ 344492.19505933],
       [ 434569.95807855],
       [ 303923.52488508],
       [ 407346.53965987],
       [ 242709.95014166],
       [ 404437.7549091 ],
       [ 436228.39392339],
       [ 670114.90654921],
       [ 342944.31478778],
       [ 434196.04909281],
       [ 402812.79004812],
       [ 391887.77531672],
       [ 992238.55185257],
       [ 774724.1576736 ],
       [ 443032.8085192 ],
       [ 423517.53937582],
       [ 342879.28084133],
       [ 781616.36339903],
       [ 179891.91109775],
       [ 779181.90641154],
       [ 384231.43486128],
       [ 462727.61105976],
       [ 511919.36044549],
       [ 548002.05372043],
       [ 754575.7549182 ],
       [ 270005.76002139],
       [ 321271.92810882],
       [ 576915.83509169],
       [ 452849.89186657],
       [1135977.60379402],
       [ 554609.88317014],
       [ 363687.79828542],
       [1183179.0063179 ],
       [ 690074.60270137],
       [ 852803.56203135],
       [ 627792.82455005],
       [ 431920.98251484],
       [ 546010.94573856],
       [ 604286.25556506],
       [ 255311.90463635],
       [ 284369.89831036],
       [ 427427.58821604],
       [1251521.40018338],
       [1280397.31296561],
       [ 434974.35341881],
       [ 536927.7188899 ],
       [ 503226.9599506 ],
       [ 410016.21442763],
       [ 588091.30275038],
       [ 205114.28716891],
       [ 234482.64544492],
       [ 356396.26499409],
       [ 210470.50429304],
       [ 358287.67409034],
       [ 647984.29895592],
       [ 657782.53268884],
       [ 125629.5642385 ],
       [ 692463.88992233],
       [ 648178.97673212],
       [ 848255.53842451],
       [ 721710.22325203],
       [ 422667.13544586],
       [ 419363.56232655],
       [ 522563.04569117],
       [ 349209.41941941],
       [ 497435.29979663],
       [ 625186.25983102],
       [ 595297.18929339],
       [ 332032.35119793],
       [ 393793.83904242],
       [ 658609.73443273],
       [ 633141.85916165],
       [ 386043.94644924],
       [ 329752.6168364 ],
       [ 484469.72095087],
       [ 730886.55658899],
       [  94598.30693272],
       [ 439711.37317391],
       [ 426208.64711868],
       [ 683820.17152478],
       [ 964697.80948911],
       [ 426341.85673332],
       [ 876115.1157883 ],
       [ 362811.08595521],
       [ 564781.90168716],
       [ 598877.51524789],
       [ 912282.38042416],
       [ 686382.62877272],
       [ 410486.61320234],
       [ 484784.80846198],
       [ 486755.71213199],
       [ 541609.59552604],
       [ 292221.53072613],
       [ 492395.04784533],
       [1316578.67162738],
       [ 912522.65285234],
       [ 514010.60517843],
       [ 248548.98723437],
       [ 831390.30537844],
       [ 642988.35708399],
       [ 355690.30613482],
       [ 999594.28480126],
       [ 259389.59710995],
       [ 546142.44776843],
       [ 706161.16137599],
       [ 712579.72610706],
       [1655976.57978091],
       [ 422969.83687595],
       [ 417651.27503881],
       [ 318579.10732755],
       [ 641014.43196168],
       [ 593552.88043172],
       [ 326456.04276081],
       [ 443936.19867901],
       [ 439498.49498208],
       [ 420086.14084959],
       [ 255006.1088889 ],
       [ 292920.60278968],
       [ 491213.73578281],
       [ 558232.54742966],
       [ 524154.68234733],
       [ 521804.58573206],
       [ 771081.88237266],
       [ 934954.8942066 ],
       [ 831560.57990468],
       [ 314881.37705172],
       [ 311831.02064679],
       [ 947867.46864961],
       [ 458801.36878153],
       [1222639.33509628],
       [ 363803.38831421],
       [ 439360.48561197],
       [ 519309.53198483],
       [ 225595.41997791],
       [ 483719.27676087],
       [ 643693.53835476],
       [ 745603.03088686],
       [ 252553.32455833],
       [ 529398.87899046],
       [1074667.47216004],
       [ 682672.06880566],
       [ 482400.16492451],
       [ 281905.17260632],
       [ 638265.00584997],
       [ 337231.35029337],
       [ 279848.56296663],
       [ 729944.82891612],
       [ 828753.19266979],
       [ 364946.08898516],
       [ 864945.17494645],
       [ 393347.3278536 ],
       [ 503131.49448192],
       [ 659287.16896018],
       [1403003.74940561],
       [ 351982.99032132],
       [ 486920.31100798],
       [ 409966.63159878],
       [ 328398.73016988],
       [ 387335.05246873],
       [ 139827.13878807],
       [ 608012.12187797],
       [ 556330.44174478],
       [ 262612.66225403],
       [1341931.30651335],
       [ 311577.01322864],
       [ 379368.72527872],
       [ 631906.36110896],
       [ 374749.31071982],
       [1162934.13969654],
       [ 315607.29724271],
       [ 671073.41136109],
       [ 660142.82098367],
       [1169329.92459717],
       [ 730805.85278784],
       [ 707655.57007032],
       [ 376344.5859955 ],
       [ 341949.43357687],
       [ 537189.64848568],
       [ 636233.29193654],
       [1180843.65559204],
       [ 551794.28826354],
       [ 598030.59528469],
       [ 650011.50786623],
       [ 304960.41089708],
       [ 368010.17169928],
       [ 290543.89363252],
       [ 288080.38543449],
       [ 416132.07477532],
       [ 748953.12946277],
       [ 452183.31221652],
       [ 412541.71819161],
       [ 772084.61410805],
       [ 728526.54195077],
       [ 480220.86755026],
       [ 261888.00894995],
       [ 278482.45388779],
       [ 886638.77800188],
       [ 422049.19929216],
       [ 586360.42217407],
       [1012000.67704116],
       [ 279288.54507875],
       [ 377247.34632485],
       [ 674471.16462295],
       [ 202618.69613964],
       [ 562897.82133702],
       [ 710514.0239783 ],
       [ 325588.21543607],
       [ 621707.66145987],
       [ 308253.81455564],
       [ 387978.00801134],
       [ 405205.5494999 ],
       [ 315212.07277774],
       [ 422132.05400917],
       [ 500036.58769328],
       [ 472085.84143186],
       [ 510803.72750131],
       [ 397957.53711385],
       [ 496263.22025998],
       [ 701276.73931077],
       [ 608920.48251008],
       [ 867995.57669692],
       [ 894549.88544231],
       [ 662937.585231  ],
       [ 703440.81135946],
       [ 740195.39615106],
       [ 417923.52749979],
       [ 573908.86575368],
       [ 480889.08482621],
       [ 611350.7467285 ],
       [ 204522.92192468],
       [ 595928.30581125],
       [ 599192.77436215],
       [ 763806.7530628 ],
       [ 460390.8257785 ],
       [ 310214.86757783],
       [1266536.36394505],
       [ 606734.25058799],
       [ 379791.18998152],
       [ 331967.44745566],
       [ 333265.53935265],
       [ 305223.66434685],
       [ 681360.55341142],
       [ 617743.14898804],
       [ 196491.86446259],
       [ 885879.64447579],
       [ 202888.04000848],
       [ 631862.41101703],
       [1128419.42683096],
       [ 811375.52517494],
       [ 510355.84342436],
       [ 389157.24079849],
       [ 923948.3456425 ],
       [ 598233.84895669],
       [ 456744.26636199],
       [1105388.29592681],
       [ 211958.20571495],
       [ 660122.1141843 ],
       [ 797560.55613114],
       [ 536845.71053882],
       [ 460811.71079741],
       [ 236786.31822012],
       [ 212638.83538988],
       [ 372874.6453318 ],
       [ 567768.95987858],
       [ 620432.97423441],
       [1898889.621387  ],
       [ 309989.89933507],
       [ 376623.17305878],
       [ 311016.39476081],
       [ 697440.45413248],
       [ 277244.25114506],
       [ 560851.90832652],
       [ 250932.68896616],
       [ 386524.31795202],
       [ 415158.96321857],
       [ 668767.90150156],
       [ 909805.8206276 ],
       [ 667572.94141035],
       [ 291079.844639  ],
       [ 311679.06122091],
       [ 782992.8020408 ],
       [ 396061.88320043],
       [ 509728.05985086],
       [ 674717.34582192],
       [ 588212.54890054],
       [ 581844.99489046],
       [ 562726.35065972],
       [ 620542.2419439 ],
       [ 517710.13397118],
       [ 393907.98273843],
       [ 628954.09268195],
       [1148508.5023409 ],
       [ 337342.82649252],

In [20]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [21]:
mean_absolute_error(y_test,y_pred)

167029.89828784278

In [22]:
mean_squared_error(y_test,y_pred)

68186648527.45037

In [23]:
r2_score(y_test,y_pred)

0.5443803035807766