In [ ]:
import pandas as pd
df=pd.read_csv('SOCR-HeightWeight.csv')

In [ ]:
df.head(5)

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

In [ ]:
x=df[["Height(Inches)"]]
y=df[["Weight(Pounds)"]]

In [ ]:
df.isnull().any()

Index             False
Height(Inches)    False
Weight(Pounds)    False
dtype: bool

In [ ]:
df.isnull().sum()

Index             0
Height(Inches)    0
Weight(Pounds)    0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split #sk learn->scikit-learn

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2) #test-size=>total 10 ,test=2,train=8

In [ ]:
x_train

       Height(Inches)
9616         67.89264
13585        66.40242
20711        65.25360
3031         71.21679
20978        68.88230
...               ...
16862        66.60702
17508        69.78746
7387         67.40434
8017         66.34532
19517        65.67362

[20000 rows x 1 columns]

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model=LinearRegression()

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
model.predict(x_test)

array([[133.77056103],
       [124.10421805],
       [137.72023204],
       ...,
       [118.71780762],
       [128.09764207],
       [127.43805859]])

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
mean_absolute_error(y_test,y_pred)

7.965808176665058

In [ ]:
mean_squared_error(y_test,y_pred)

100.80395531182202

In [ ]:
r2_score(y_test,y_pred)

0.2540878389464528

In [ ]:
import joblib
joblib.dump(model,"Linear.pkl")

['Linear.pkl']